const User    = require('../models/User');
const Student = require('../models/Student');
const Group   = require('../models/Group');

const ALLOWED_STAFF_ROLES = ['faculty', 'counselor', 'marketing', 'office_staff'];

// GET /api/admin/dashboard
exports.getDashboardStats = async (req, res) => {
  try {
    const [totalStudents, totalFaculty, totalCounselors, totalMarketing, totalOfficeStaff] = await Promise.all([
      Student.countDocuments({ isActive: true }),
      User.countDocuments({ role: 'faculty',       isActive: true }),
      User.countDocuments({ role: 'counselor',     isActive: true }),
      User.countDocuments({ role: 'marketing',     isActive: true }),
      User.countDocuments({ role: 'office_staff',  isActive: true }),
    ]);
    const Fee       = require('../models/Fee');
    const { Leave } = require('../models/index');
    const [totalFeeCollected, pendingLeaves] = await Promise.all([
      Fee.aggregate([{ $match: { status: 'paid' } }, { $group: { _id: null, total: { $sum: '$amount' } } }]),
      Leave.countDocuments({ status: 'pending' }),
    ]);
    res.json({
      totalStudents,
      totalFaculty,
      totalCounselors,
      totalMarketing,
      totalOfficeStaff,
      totalStaff: totalFaculty + totalCounselors + totalMarketing + totalOfficeStaff,
      totalFeeCollected: totalFeeCollected[0]?.total || 0,
      pendingLeaves,
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// POST /api/admin/students
exports.createStudent = async (req, res) => {
  try {
    const {
      name, email, password, phone,
      course, batch, semester, dob,
      address, guardianName, guardianPhone, bloodGroup,
    } = req.body;

    const existing = await User.findOne({ email });
    if (existing) return res.status(400).json({ message: 'Email already registered' });

    const user = await User.create({
      name, email,
      password: password || 'PIMT@1234',
      role: 'student',
      phone,
      createdBy: req.user._id,
    });

    const student = await Student.create({
      user: user._id,
      course, batch,
      semester: semester || 1,
      dob, address,
      guardianName, guardianPhone, bloodGroup,
    });

    res.status(201).json({
      message:      'Student created successfully',
      deviceUserId: user.deviceUserId,
      rollNumber:   student.rollNumber,
      user: {
        id:           user._id,
        name:         user.name,
        email:        user.email,
        deviceUserId: user.deviceUserId,
      },
      student: { id: student._id, rollNumber: student.rollNumber },
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// GET /api/admin/students
exports.getStudents = async (req, res) => {
  try {
    const students = await Student.find()
      .populate('user', 'name email phone isActive deviceUserId')
      .sort('rollNumber');
    res.json(students);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// PATCH /api/admin/students/:id
exports.updateStudent = async (req, res) => {
  try {
    const allowed = ['rollNumber', 'course', 'batch', 'semester', 'bloodGroup'];
    const updates = {};
    allowed.forEach(f => { if (req.body[f] !== undefined) updates[f] = req.body[f]; });
    const student = await Student.findByIdAndUpdate(req.params.id, updates, { new: true });
    res.json({ message: 'Student updated', student });
  } catch (err) {
    if (err.code === 11000) return res.status(400).json({ message: 'Roll number already in use' });
    res.status(500).json({ message: err.message });
  }
};

// DELETE /api/admin/students/:id
exports.deleteStudent = async (req, res) => {
  try {
    const student = await Student.findByIdAndUpdate(req.params.id, { isActive: false });
    if (!student) return res.status(404).json({ message: 'Student not found' });
    await User.findByIdAndUpdate(student.user, { isActive: false });
    res.json({ message: 'Student deactivated' });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// POST /api/admin/sub-admins  — supports all 4 new roles
exports.createSubAdmin = async (req, res) => {
  try {
    const { name, email, password, role, phone, basicSalary } = req.body;

    if (!ALLOWED_STAFF_ROLES.includes(role))
      return res.status(400).json({ message: `Role must be one of: ${ALLOWED_STAFF_ROLES.join(', ')}` });

    const existing = await User.findOne({ email });
    if (existing) return res.status(400).json({ message: 'Email already in use' });

    const user = await User.create({
      name, email, password, role, phone,
      basicSalary: basicSalary || 0,
      createdBy: req.user._id,
      // deviceUserId auto-generated by User model pre-save hook
    });

    res.status(201).json({
      message: 'Staff created',
      user: {
        id:           user._id,
        name:         user.name,
        email:        user.email,
        role:         user.role,
        deviceUserId: user.deviceUserId,
        basicSalary:  user.basicSalary,
      },
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// GET /api/admin/sub-admins
exports.getSubAdmins = async (req, res) => {
  try {
    const subAdmins = await User.find({ role: { $in: ALLOWED_STAFF_ROLES } })
      .select('-password')
      .sort('name');
    res.json(subAdmins);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// DELETE /api/admin/sub-admins/:id
exports.deleteSubAdmin = async (req, res) => {
  try {
    await User.findByIdAndUpdate(req.params.id, { isActive: false });
    res.json({ message: 'Staff deactivated' });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// GET /api/admin/enquiries
exports.getEnquiries = async (req, res) => {
  try {
    const { Lead } = require('../models/index');
    const enquiries = await Lead.find().populate('assignedTo', 'name role');
    res.json(enquiries);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// ── GROUP MANAGEMENT ──

// GET /api/admin/groups
exports.getGroups = async (req, res) => {
  try {
    const groups = await Group.find({ isActive: true })
      .populate('headFaculty', 'name email role')
      .populate({ path: 'students', populate: { path: 'user', select: 'name' } })
      .sort('-createdAt');
    res.json(groups);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// POST /api/admin/groups
exports.createGroup = async (req, res) => {
  try {
    const { name, description, headFaculty, course, batch, studentIds } = req.body;
    if (!headFaculty) return res.status(400).json({ message: 'Faculty head is required' });

    // Verify headFaculty is actually a faculty member
    const faculty = await User.findOne({ _id: headFaculty, role: 'faculty' });
    if (!faculty) return res.status(400).json({ message: 'Selected user is not a faculty member' });

    const group = await Group.create({
      name, description, headFaculty, course, batch,
      students:  studentIds || [],
      createdBy: req.user._id,
    });

    const populated = await Group.findById(group._id)
      .populate('headFaculty', 'name role')
      .populate({ path: 'students', populate: { path: 'user', select: 'name' } });

    res.status(201).json(populated);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// DELETE /api/admin/groups/:id
exports.deleteGroup = async (req, res) => {
  try {
    await Group.findByIdAndUpdate(req.params.id, { isActive: false });
    res.json({ message: 'Group deleted' });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};